#ifndef BINPACKINGPROBLEM_PARAMETERS_H
#define BINPACKINGPROBLEM_PARAMETERS_H

namespace parameters {
    // GENETIC ALGORITHM
    int POPULATION_SIZE = 100;
    int TERMINAL_CONDITION = 1;
    int CROSSOVER_METHOD = 1;
    int MUTATION_METHOD = 1;

}



#endif //BINPACKINGPROBLEM_PARAMETERS_H
